export async function cleanupAbandonedCheckouts(){
    const date_now = Date.now();
    try {
       
    } catch (error) {
        console.error("Something went wrong while cleaning the checkouts", error);
    } 

}